# Generated by Django 5.1.5 on 2025-01-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_candidato_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('estado', models.CharField(max_length=2)),
                ('partido', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=10)),
                ('cnpj', models.CharField(max_length=18)),
                ('escopo', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('foto_identidade', models.FileField(upload_to='uploads/')),
                ('comprovante_residencia', models.FileField(upload_to='uploads/')),
                ('documento_aplicacao', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
