# Generated by Django 5.1.5 on 2025-01-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_candidato_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='endpoint',
            field=models.CharField(default='candidato', max_length=50),
            preserve_default=False,
        ),
    ]
